### PR TITLE
Update isActive to not rely on Sessions

### PR DESCRIPTION
**Pull request by guilhermedecampo**
Using the iron-router API to get the name of the route.

### CODE REVIEW

**Comment by nickw** [comment]
Unfortunately this needs to rely on `Session` since tabs aren't necessarily tied to routes. e.g. take a look at the behavior of the tabs in http://meteorhunt.meteor.com/ (especially the profile tab).

**Comment by guilhermedecampo** [comment]
Could not find any reason on profile tab that explains that is not tied to routes.

Can you be more specific?

**Comment by nickw** [comment]
In a mobile app the tab bar represents overall sections of the app, not individual screens. So in the Meteor Hunt example when I click on the "profile" tab I am in the "profile section" of the app and that tab should stay highlighted until I choose another tab. From a user's profile I can navigate to individual posts that a user has voted on. If the tabs were tied to routes, the highlighted tab would change when I navigated to the post detail route.

**Comment by guilhermedecampo** [comment]
Yes you are right! 

I'm having a problem with the hardware button in android which doesn't change the tabs active class.
Maybe we can fix this in another way? Do you have any thoughts about this?

Thanks for the explanation :+1:

**Comment by nickw** [comment]
I think we just need to implement the hardware back button: https://github.com/meteoric/meteor-ionic/issues/71

**Comment by nickw** [comment]
Well technically the back button _shouldn't_ change the tabs. Each tab should have it's own navigation stack. At least that's the way it works on iOS.

**Pull request closed without merging**
