### PR TITLE
Update GUIDE.md and ionTab.js

### PR DESCRIPTION
**Pull request by elie222**

### CODE REVIEW

**Comment by nickw** [comment]
@elie222 can you fix the conflicts on this? Once you do I'll merge this in and release the latest version. Thanks!

**Comment by elie222** [comment]
Fixed the conflict

**Comment by elie222** [comment]
@nickw this branch was never merged

**Comment by nickw** [comment]
@elie222 it looks like the Popups section of the docs has some issues (maybe caused by a previous merge):
screen shot 2015-08-10 at 12 43 21 pm

**Comment by elie222** [comment]
Yup. Was a merge fail. Should be good now.

**Comment by nickw** [comment]
Actually it looks like the last paragraph and code block should be a part of the `Modals` section above.

**Comment by elie222** [comment]
Okay! Sloppy work by me! Will look at it again tomorrow

**Comment by elie222** [comment]
I think it should be alright now

**Pull request merged**
