### PR TITLE
Adjusted the align data source to be this.data

### PR DESCRIPTION
**Pull request by digilord**
this.data holds the alignTitle attribute for the ionHeaderBar when using the ionNavBar.

### CODE REVIEW

**Comment by findingmeteor** [comment]
If this.data is null you get:

```
 Exception from Tracker afterFlush function: Cannot read property 'alignTitle' of null
TypeError: Cannot read property 'alignTitle' of null
    at IonHeaderBar.alignTitle (http://localhost:3000/packages/meteoric_ionic.js?8d5f600e2a0f01e224c5ba01fd90c6247c7be240:1252:26)
    at Template.ionNavBar.rendered (http://localhost:3000/packages/meteoric_ionic.js?8d5f600e2a0f01e224c5ba01fd90c6247c7be240:1936:27)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:3008:21)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1733:14
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1732:15
    at Tracker.flush (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:448:11)
```

A workaround to prevent the TypeError is using ionNavBar with alignTitle:

    {{> ionNavBar alignTitle="something"}}

Is this the desired behaviour?

**Comment by nickw** [comment]
No, it's not the desired behavior. We are constantly fighting with meteor over the `this.data` property inside templates. I'll just need to sit down and figure out a global fix for this in all the components. However it's very strange that I haven't yet experienced this issue once in any of my apps or demos.

**Comment by findingmeteor** [comment]
Thanks for the reply @nickw  
I'm using Meteor 1.0.3.1 and I tested this on Chrome 40.0.2214.94 (64-bit) and Firefox 37.0a2 (2015-01-21) 

I created this repo to reproduce the issue: https://github.com/findingmeteor/minimal-meteroic

I hope it helps

**Comment by nickw** [comment]
Thanks for the reproduction:) I just pushed something that should fix it - let me know!

**Comment by findingmeteor** [comment]
Awesome! Works great for me (I cloned the repo inside the packages directory to do the test).
Thanks @nickw !

**Pull request merged**
