### PR TITLE
Update Cordova Keyboard Dependency

### PR DESCRIPTION
**Pull request by benstr**

### CODE REVIEW

**Comment by codebreach** [comment]
Can you push a new version with this change, I am not sure how I can depend on this in my project. Removing and readding meteor-ionic does NOT get me this commit.

**Comment by benstr** [comment]
I can take care of that, on my todo for today @codebreach. Will update this thread.

**Comment by codebreach** [comment]
ping?

**Comment by benstr** [comment]
@codebreach version 0.2.0 has been pushed to atmosphere

**Comment by codebreach** [comment]
gacias

**Pull request merged**
